/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class HttpFilterLibraryTest {
    @Test public void testSomeLibraryMethod() {
        HttpFilterLibrary classUnderTest = new HttpFilterLibrary();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
